### ISSUE TITLE
How does it export to Prometheus DB?

### ISSUE THREAD

**Issue by ZataH** [ngosang/urbackup-exporter#1]
I might have missed something, but how am I supposed to export this to my Prometheus DB on my Grafana server?

**Comment by ngosang** [comment]
You have to edit the `config.yml` file in Prometheus to grab the metrics. I published a new release 1.1.0 and updated the documentation.
https://github.com/ngosang/urbackup-exporter#prometheus-config

**Comment by ZataH** [comment]
Thanks, I got it working now. Thank you for creating this.
