### ISSUE TITLE
Infscape support

### ISSUE THREAD

**Issue by magnored** [ngosang/urbackup-exporter#4]
Works on infscape appliance?

**Comment by ngosang** [comment]
I don't know. We use the UrBackup REST API, if it's compatible it should work.
If you find something you can open a PR with changes in the readme or in the code.

**Comment by gurhyj** [comment]
FYI I got exporter to connect to my infscape UrBackup Appliance 1.11.4 on port :80/x. A am seeing a bug with image basked backups.  But I will open a separate issue for it
