### ISSUE TITLE
KeyError: 'last_filebackup_issues'

### ISSUE THREAD

**Issue by wywywywy** [ngosang/urbackup-exporter#6]
Just set up UrBackup as well as the ngosang/urbackup-exporter at a new site, but got the following error.

```
2023-10-01 15:21:55 INFO     Starting UrBackup Prometheus Exporter ...
Traceback (most recent call last):
  File "/urbackup-exporter.py", line 185, in <module>
    prometheus_client.core.REGISTRY.register(UrBackupCollector(
  File "/usr/local/lib/python3.11/site-packages/prometheus_client/registry.py", line 40, in register
    names = self._get_names(collector)
            ^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/prometheus_client/registry.py", line 80, in _get_names
    for metric in desc_func():
  File "/urbackup-exporter.py", line 96, in collect
    self.float_or_default(client["last_filebackup_issues"], 0.0))
                          ~~~~~~^^^^^^^^^^^^^^^^^^^^^^^^^^
KeyError: 'last_filebackup_issues'
```

What is `last_filebackup_issues`? It sounds like the UrBackup REST API doesn't return this particular attribute for some reasons.

I'm on v2.5.31 server, with exporter v1.1.3 in k8s.

I've been using 2.3.x in another site for years without issue.

**Comment by ngosang** [comment]
The last release was tested with UrBackup server 2.4.13. Probably they removed that attribute from the API in newer versions.
I moved to Restic backup and I'm not maintaining this repository anymore. If you want, you can open a PR to fix the issue but make sure it's blackguards compatible. Thank you!

**Comment by wywywywy** [comment]
Ok no problem thanks for letting us know.

I'll give this a go.

**Comment by ngosang** [comment]
@wywywywy https://github.com/ngosang/urbackup-exporter/releases/tag/1.2.0
